### ISSUE TITLE
Intro

### ISSUE THREAD

**Issue by gorryfair** [NicoKos/QUIC_HIGH_BDP#104]
Probably would be good to start with a generic para that says something like (needs edit).

Each transport connection typically starts without knowledge of the path between the endpoints, and then uses implicit signals from the network to discover the properties of the path that it will. This information is used to adapt the transport mechanisms to the network path. For example, an Internet transport endpoint is unable to determine a safe rate at which to start or continue their transmission, and uses slow-start to determine a safe rate.

**Comment by NicoKos** [comment]
Included in PR #110
