### ISSUE TITLE
Appendix - some suggested text

### ISSUE THREAD

**Issue by gorryfair** [NicoKos/QUIC_HIGH_BDP#106]
>> I think the method is basically good, but we need to articulate a little clearer.

The initial window is considered a safe starting point for an unknown path to avoid adding congestion to a congested network. The general assumption is that a path does not currently suffer persistent congestion, and therefore the initial window is applicable until feedback about the path is received.  The resulting initial sending rate is tentative until the capacity is confirmed to be available. If there is loss within this initial transmission, then this could be evidence that the path is congested, and the sender needs to adjust to the congestion.
 
Significant loss could be an indication of congestion collapse - i.e. persistent loss, requiring back-off of the sending rate.

If however, the transmission of IW is confirmed in the first RTT of data, and also the path is determined to be also similar to that of a recent previous session (e.g., similar RTT), the method permits the sender to use the previous path information as an input to help it now determine a safe rate. One possibility is to immediately jump to a new sending rate that is derived from the previously sustained rate. 

<< e.g., BBR, Jump-Start from Mark Allman etc >>> 
<< May also need to allow some space for other flows to have started (or start coincident with the current flow), should the rate be 1/n of the last cwnd? >>

Such changes are based on:
* The sender must provide some way of detecting if the path has not changed.
* The sender needs to provide a safe way of responding if the capacity has changed (either the set/configuration of devices and link on-path; or the capacity remaining has changed due to other traffic sharing the path).
* The sender must provide a significant reduction if there is evidence of potential "Congestion Collapse" [RFC2914]. This "occurs when an increase in the network load results in a decrease in the useful work done by the network." Classical congestion collapse is a stable condition that can result in throughput that is a small fraction of normal [RFC0896].

**Comment by NicoKos** [comment]
Thank you for the text. I have just added some text at the end to reflect the congestion collapse aspect. 
In PR #110
