### ISSUE TITLE
Security Considerations of Usage of Ticket

### ISSUE THREAD

**Issue by gorryfair** [NicoKos/QUIC_HIGH_BDP#11]
The way the ticket is presently described requires the server to respond. This raises a question whether this can result in a DoS attack on a server by simulatenously requesting additional resources from many clients.

This could be resolved by:
• Permitting a server not to honour the reques when it is resource-limited.

**Comment by NicoKos** [comment]
Thanks. I have added a line in that sense. Closed by PR #18
