### ISSUE TITLE
1-RTT or previous connection  ?

### ISSUE THREAD

**Issue by emile22** [NicoKos/QUIC_HIGH_BDP#125]
As said at the end of the section 2 "this document proposes safety guidelines on how to safely apply previously measured parameters to 0-RTT connections". Currently the document focuses on the case where the previous connection is a 1-RTT connection. It is just a matter of wording but it should cover the cases where previous connections are 0-RTT.

**Comment by NicoKos** [comment]
I think this is solved in https://github.com/NicoKos/QUIC_HIGH_BDP/commit/17fd7bba2d35f76e5e380f380bbe4d86c80506c7
