### ISSUE TITLE
malicious server

### ISSUE THREAD

**Issue by emile22** [NicoKos/QUIC_HIGH_BDP#131]
Do we need to add the case of a malicious server ?

https://github.com/NicoKos/QUIC_HIGH_BDP/blob/651c73403fc7e0eedce36a1f03896454c5014147/ietf-document/draft-0rtt-bdp/draft-kuhn-quic-0rtt-bdp-09.xml#L229

**Comment by gorryfair** [comment]
Perhaps, what would say?

From a CC perspective, the server is able to do anything - good or bad, and the network trusts its CC behaviour, or deploys a circuit breaker to protect itself.

**Comment by NicoKos** [comment]
is it solved by https://github.com/NicoKos/QUIC_HIGH_BDP/commit/17fd7bba2d35f76e5e380f380bbe4d86c80506c7 ?
