### ISSUE TITLE
CWIN?

### ISSUE THREAD

**Issue by gorryfair** [NicoKos/QUIC_HIGH_BDP#133]
There's still one case of CWIN ... Note: we need a careful check that we have labelled the "saved" values from the last session consistently with respect to the "current" values initialised in the new connection.

**Comment by NicoKos** [comment]
Is it solved by https://github.com/NicoKos/QUIC_HIGH_BDP/commit/17fd7bba2d35f76e5e380f380bbe4d86c80506c7 ?

**Comment by gorryfair** [comment]
Solved.
