### ISSUE TITLE
Terminology

### ISSUE THREAD

**Issue by gorryfair** [NicoKos/QUIC_HIGH_BDP#134]
Some terms

IW:  Initial window (e.g. from the standard).
BDP: defined above.
cwnd: Current congestion window used by server (bytes allowed in flight by CC);
saved_cwnd: Congestion window preserved from a previous connection;
rtt: Current RTT;
saved_rtt: RTT preserved from a previous connection;

etc.

**Comment by NicoKos** [comment]
There is a new terminology section. 
Is that ok ? 
https://github.com/NicoKos/QUIC_HIGH_BDP/commit/17fd7bba2d35f76e5e380f380bbe4d86c80506c7
