### ISSUE TITLE
IP address parameter is under specified

### ISSUE THREAD

**Issue by huitema** [NicoKos/QUIC_HIGH_BDP#135]
In BDP draft, the BDP frame is defined as:
```
    BDP Frame {
     Type (i) = 0xXXX,
     Lifetime (i),
     Saved CWND (i),
     Saved RTT (i),
     Saved IP,
   }
```
The `Save IP` parameter is defined as:

*    Saved IP (saved_client_ip) : The saved_client_ip could be set to
      the IP address of the client.  The IP address of the client can be
      encoded as the preferred_address parameter [RFC9000].

That does not work, because the preferred address parameter is specified in RFC 9000 as:
```
  IPv4 Address (32),
  IPv4 Port (16),
  IPv6 Address (128),
  IPv6 Port (16),
```
This does not fit our usage, because:

1) The BDP is measured on the specific IP address to which packets were sent. This can be IPv4 or IPv6, but not both at the same time.

2) Client side port numbers are ephemeral. The value used in the previous connection is unlikely to be reused in the next connection.

I think the specification should be changed to:
```
    BDP Frame {
     Type (i) = 0xXXX,
     Lifetime (i),
     Saved CWND (i),
     Saved RTT (i),
     Saved IP length(i),
     Saved IP (..)
   }
```
with the specification that IP length is set to either 4 (IPv4) or 16 (IPv6).

**Comment by NicoKos** [comment]
Thank you for this feedback. The draft has been adapted accordingly in PR #137
