### ISSUE TITLE
Overshooting link capacity after setting BDP during slow start

### ISSUE THREAD

**Issue by huitema** [NicoKos/QUIC_HIGH_BDP#139]
When testing the picoquic PR, I found that setting the CWIN to the estimated value during slow start leads to overshooting the link capacity. The following graph shows excessive CWIN value causing over 1000 packet losses:

![image](https://user-images.githubusercontent.com/7464128/127206839-8c5536f5-acf4-4c6b-b455-81d05f2a0ab0.png)

I think I understand what is happening. The CWIN is set to the BDP while the connection is still in "slow start" mode. During the first RTT, all packets will be acked since the CWIN was exactly at the expected value. But during the next RTT the CWIN will double, to twice the link capacity. This will only be noticed during the 3rd RTT, at which point loss are inevitable.

**Comment by huitema** [comment]
I think the solution involves some kind of blind trust in the BDP value from the frame. After applying data received in the BDP frame, the congestion engine should move to the "post slow start" state, assuming that windows, rtt and bandwidth are as specified in the BDP frame. This means going to "congestion avoidance" in RENO or Cubic, "probe_bw" in BBR. This is a bit of a harsh commitment, precluding fast adaptation if the bandwidth did change. I guess we have to develop that in an "implementation section" of the draft.

**Comment by huitema** [comment]
Verified in Picoquic that going to "congestion avoidance" in RENO after seeding the BDP parameters results in good performances, and similarly that going to the "probe_bw" mode in BBR works. There are pending issues for Cubic, as well as some issue when 0-RTT establishment fails for delay reasons, or when the BDP option is rejected because of an address change. This will need some debugging in Picoquic (https://github.com/private-octopus/picoquic/issues/1218).

**Comment by NicoKos** [comment]
This is issue can be closed when #144 is.
