### ISSUE TITLE
Minor issues too be included

### ISSUE THREAD

**Issue by gorryfair** [NicoKos/QUIC_HIGH_BDP#24]
Abstract:
- Is it better to say:
/This can accelerate the throughput/
Or
/There are use cases where this can accelerate the throughput/
---
/  At the end of a 1-RTT connection, a server can send information on
   the path to the client in a NewSessionTicket message./
could be better as:
/  At the end of a 1-RTT connection, a server can send information in a NewSessionTicket message taht describes the path to the client ./
---
/ As example, it can use this information to provide a
   throughput closer to the capacity of the path./
could be better as:
/ As example, it can use this information to provide information that may allow the congestion controller to provide a throughput closer to the capacity of the path./
---
In
/files of 15 kB  and 750 kB,/
- i'd prefer to sue "K" rather than "k" to refer to 1024 B, if you agree?
---
Section 5 title:
/5.  What happens when BDP is used incorrectly/
- add a question mark:
/5.  What happens when BDP is used incorrectly?/
---
A bold statement without qualification or a reference :-) 
/This can halve the page load
   time of a web page download./
- Maybe we should at least say:
/In some large BDP deployment scenarios trhis can halve the page load
   time of a web page download./
---
/An client which does not trust the/
should be:
/A client that does not trust the/
---

**Comment by NicoKos** [comment]
Thanks. I closed this minor edits with the PR #25
