### ISSUE TITLE
transport experts don't know how ticketSessions work. 

### ISSUE THREAD

**Issue by emile22** [NicoKos/QUIC_HIGH_BDP#35]
The draft already explains that  but it must shorter and simpler

**Comment by NicoKos** [comment]
Is it covered by : "  the server sends the 'ticket' in a NewSessionTicket record <xref target="I-D.ietf-quic-tls"/>. The structure of the NewSessionTicket includes the opaque 'ticket' and an 'extensions' field. The NewSessionTicket carries an additional field named 'early_data' that indicates to the client the maximum size of application data to insert in the 0-RTT message " ?
