### ISSUE TITLE
Method applies to TLS 1.3

### ISSUE THREAD

**Issue by gorryfair** [NicoKos/QUIC_HIGH_BDP#42]
Intro should note at end that the method is applicable to TLS 1.3 over any transport and therefore it can be used also with TCP Fast Open. It is important that re-establishment of a connection.

There should be a later section that specifically generalises this to early data over any Transport.

Gorry

**Comment by NicoKos** [comment]
I pushed some content in the Introduction to cover that (PR #58). 
For the section that generalises this, I guess a paragraph in the discussion section could make it, no?

**Comment by NicoKos** [comment]
I have updated the discussion in PR #75
