### ISSUE TITLE
NiTs on QUIC for Satcom

### ISSUE THREAD

**Issue by gorryfair** [NicoKos/QUIC_HIGH_BDP#46]
This contains a list of /old/new/ suggestions for the text:

Abstract:
- English:
/usage of/use of/
- We don't want to suggest an adaptation of the protocol should be made, but rather the protocol can adapt:
/adapted/able to adapt to users in high Bandwidth-Delay Product (BDP) network/
-
/may not be suitable for/could limit the user experience when user over an Internet path with a high Bandwidth Delay Product (BDP). /
- English:
/that has an impact on/that impact the operation of the/
- English:
/so as to how improve the/to ensure acceptable/.

---
Introduction:
- English, sentence 1, suggest replace by:
/The end-to-end performance of an application using an Internet path can be impacted by the 
Bandwidth-Delay Product (BDP) of the links and network devices forming the path. For instance, the page load time for a complex page can be much larger when the path includes a satellite link. A significant contribution to this reduced performance arises from the initialisation and design of transport mechanisms./
-
/may not be suitable for/could limit the user experience when user over an Internet path with a high BDP. /
- English:
/so as to how improve the/to ensure acceptable/.
---
Large BDP connections:
- Could we change to:
/Large BDP connections/Operating over a path with a large BDP/
/terrestrial networks/paths only using terrestrial links/
/with:/in their path characteristics:/
- change?
/A high loss-rate/Some systems can exhibit a high loss-rate/
- add to list:
/Employ radio resource management (often using techniques similar to cellular mobile or DOCSIS cable networks, but differing to accommodate the satellite propagation delay).
/Highly asymmetric links/Highly asymmetric links (in terms of capacity and one-way delay)/
/impact on/impact on the performance of/

/Maximum windows sizing/Size of windows required/
/losses/loss/
/end server/endpoint/ ?
/may not be relevant/ ... what does that mean?
+ add /The performance of end-to-end retransmission is also impacted when using a high RTT path./
/transmission for a/during slow start for/
---
TCP split solution
- Capitalise section headers: /TCP Split Solution/
- Define /PEP/
/deployed in/deployed in current/
/functionalities/functions/
/going from/originating at/
/end user/endpoint/
/behind terminal/connected via a satellite terminal/
/TCP SYN/TCP SYN packets/
/as an end user/act on behalf of the endpoint/
/split specifically tune/the split solution specifically tunes/
/that is measured./. The tuning can be achieved using a priori information about the satellite system and/or by measuring the properties of the network segment that includes the satellite system./
/can hardly embed/often are unable to track/
+ Add:
/The methods configured in the split proxy usually continue to be used until a split solution is finally updated. This can delay/negate the benefit of any end-to-end improvements./

Section 4.2
+ Add after Wifi-losses/
/Although the benefits needed to weighed against the additional capacity in introducing end-to-end FEC and the potential to use link-local ARQ and/or link-adaptive FEC./

Section 4.4
+Add:
/TCP Performance Implications of Network Path Asymmetry [RFC3449] describes a range of mechanisms that can mitigate the impact of path asymmetry. Many of these mitigations have been deployed in satellite systems, often as a mechanism within a PEP. Despite their benefits over paths with a high asymmetry of capacity, most mechanisms rely on being able to inspect and/or modify the transport layer header information of TCP ACK packets. This is not possible when the transport layer information is encrypted./

**Comment by NicoKos** [comment]
Closed by PR #48
