### ISSUE TITLE
Add that the "issues" arise when VPN or IPsec is used.

### ISSUE THREAD

**Issue by gorryfair** [NicoKos/QUIC_HIGH_BDP#47]
Section 5:

It seems currently that we say there are issues for QUIC... which isn't really true,  because we don't really say:

Many of the issues identified already exist for any encrypted transport service that uses a path that employs encryption at the IP layer. This includes endpoints that utilise IPsec at the network layer, or use VPN technology over the satellite network segment. These uses are unable to benefit from enhancement within the satellite network segment, and often the user is unaware of the presence of the satellite link on their path, except through observing the impact it has on the performance they experience.

**Comment by NicoKos** [comment]
Closeb by PR #51
