### ISSUE TITLE
What is the server required to do with a session ticket?

### ISSUE THREAD

**Issue by gorryfair** [NicoKos/QUIC_HIGH_BDP#8]
The mechanism as specified appears to believe that the server MUST implement something when it receives this ticket. I'd argue that this is too strong, and it would be better to update the spec to ALLOW the server to make changes when it receives the session ticket.

I think this is necessary because:
(1) The server that receives the ticket is not necessarily the same as originated the ticket and such a server will disregard the 0-RTT connection and restart the connection. Effectively ignoring the ticket.
(2) A server that once had sufficient resources to consdier optimising for different path characteristics, could later find itself more constrained and decide not to honour these when the connection is resumed.

This would effect the text:
"The server will optimize the reopening of the session upon reception of this opaque ticket."
- would become something like:
"The server SHOULD optimize the reopening of the session upon reception of this opaque ticket."
- or MAY  (and state that this is desirable).
--
Later it states:
"It uses this information to provide a throughput closer to the capacity of the path."
- would become something like:
"It can use this information to provide a throughput closer to the capacity of the path."
---
"The presence of the "BDP_data" extension field in the NewSessionTicket informs the client that the  server will actively take action to improve its throughput when the session will restart."
- would become something like:
"The presence of the "BDP_data" extension field in the NewSessionTicket informs the client that the  server can actively take action to improve its throughput when the session will restart."

**Comment by NicoKos** [comment]
Thanks. We did not indeed cover much the requirements aspects at the server side. I have included your suggestions in PR #17.
