### ISSUE TITLE
Intro and abstract

### ISSUE THREAD

**Issue by gorryfair** [NicoKos/QUIC_HIGH_BDP#85]
Abstract & Intr of 0rtt-bdp-06 needs a little more work to make it readable.

"optimization of the egress traffic."
Don't like /optimization/ we should say what it does - if this allows for faster-startup of flows .... we should say.

I don't know what was intended as / the egress traffic/ - is this packets from the server?

- unsure what is intended by: " it indicates to the client the number of bytes it is allowed
   to send in the first packet sent when reconnecting -packet? initial data?
- reconnect? is that the word in QUIC?

/ingress traffic exchange/ ingress? packets to the server?

/The memo focuses on cases with high Bandwidth Delay Product (BDP) and
   constrained situations. /
- Constrained situation?

**Comment by NicoKos** [comment]
Thanks for this. I will update the text ASAP to make this clearer. 
In short : optimization => faster-startup and buffer sizes adaptations
Egress : packets from the server (will be precised)
Reconnect : I will use the wording of the current QUIC document
Constrained : Clients with limited buffer space

**Comment by NicoKos** [comment]
Proposed text in PR #93
