### ISSUE TITLE
Last BDP isn't really cwnd?

### ISSUE THREAD

**Issue by gorryfair** [NicoKos/QUIC_HIGH_BDP#86]
last_bdp (0x000X): The BDP measured on the previous connection by
      the server.  It is an integer in unit of bytes.  Using the
      congestion_window defined in [I-D.ietf-quic-recovery], last_bdp
      can be set to congestion_window.

This value isn't actually the BDP. The condo can grow to substantially more than the BDP, and includes the overshoot. For a rate limited application, e.g. where flow control limits, the condo can grow to an arbitrary large size if cwv is not correctly implemented. for these reasons the cwnd is a very course estimate of BDP and we need to be careful how it is used.

I think for the method I proposed as a straw man, we don't actually need an accurate BDP measure, so that is not a fundamental problem... never-the-less we should not ignore that the cwnd can be larger than the BDP.

**Comment by NicoKos** [comment]
We kept the information on the BDP that had been used in previous connections. 
The idea was more to have information on the trend for the BDP. 
I agree that flow control may limit the connection and the CWND would grow without accuratly reflecting the actual BDP - so using CWND may not be accurate. 

Looking at the parameters defined in the recovery draft, using the bytes_in_flight parameter would be an alternative as identifying the BDP. 
What do you think ?

**Comment by gorryfair** [comment]
I think actually it's better. 

It can still be inflated - because it can still include buffering and overshoot - so we need to be careful in how it is used - but with one BDP of buffer * one BDP of overshoot, FS can be 2*2*BDP. In most cases it can be expected to be nearer BDP:-).

**Comment by NicoKos** [comment]
In RFC7928, when discussing congestion levels, we point to [1] where the sum of the bandwidth-delay product and the maximum buffer size is considered. 
I guess using the bytes_in_flight parameter is the closer we can have if we do not want to go further into the details of the congestion control.

[1] Morris, R., "Scalable TCP congestion control", IEEE INFOCOM, DOI 10.1109/INFCOM.2000.832487, 2000

**Comment by NicoKos** [comment]
text proposed in PR #91
