### ISSUE TITLE
Strawman algorithm for using initial max packet number

### ISSUE THREAD

**Issue by gorryfair** [NicoKos/QUIC_HIGH_BDP#88]
Suppose a path is declared as having a large RTT and large BDP.

If the client returns encrypted info form it's IP address, the server can verify the client is indeed at the same IP address. Using the information in the exchange it can also understand if the RTT was large - and if the BDP was sufficiently large to enable this optimisation.

I suggest that the IW is normally regarded as safe, providing it is paced. Hence we need to pace any IW - so my proposal suggests we pace over the interval

MIn(min_rtt, 100ms) - that provides sufficient spreading that the IW is not aggressively increased. The value 100ms is a value chosen because for most Internet paths this will not results in packets separated in time (spread), preventing a start-up burst from starving other flows.

The sender using this extension is allowed to send multiple 100ms windows of packet bursts, each containing the IW of packets (10 in this specification).

For example, if the RTT were 600ms then then there would be 6 rounds of IW=10 paced packets, a total of 60 packets. Using traditional slow start this would correspond to saving approximately 2 RTTs of cwnd increases.
If the RTT were 1 second, there would be 10 rounds of IW=10 paced packets, a total of 100 packets. Using traditional slow start this would correspond to saving approximately 2 RTTs of cwnd increases.
Note that this method provides significant benefit to GEO satellite services, but this specific method does not benefit low RTT services.

The maximum number of initial data packets that can be sent without acknowledgement needs to be chosen to avoid congestion collapse. The value of flight-Size/10 is used for this limit. This value is taken as an estimate that is expected to be sufficiently below the capacity of the path - this is not known, and is purely an estimate based on  the data exchanged in the last connection - we do not use cwnd, because this can grow beyond flight size, but we recognise that flight size can still be larger than the capacity due to buffering on the path and to reduce the potential starvation of other flows, we reduce to 1/10 of the capacity that was last used.

Another factor is to ensure that flow-control is somehow captured in the start-up. There could be a client that is resource-constrained and does not wish to use a larger window. The client could simply not return the extension information. A alternative would be to signal the maximum initial window size the client is allowing the server to use - equivalent to controlling the credit for flow control. 

Discussion of safe use

If the server then utilises the congestion control info that it has been passed, it will anticipate a large delay. An increased window of  data would be pacing over the anticpated RRT, say 1 sec. The method needs to choose an increased IW that is conservative (say ... for example, this was only enabled when RTT>100mS? and then the total size of initial data is only scaled by allowing an increase from the normal that is IW * cached_min_RTT/0.1).

   If the RTT is correct, the client responds 1 RTT later all is well.

   If it happens that the client's RTT is smaller (for whatever reason),
   the rate of transmission is still not likely higher than the client
   would normally experience (because it is paced to a rate based on a
   higher RTT). The first ACK will be received before the entire IW has
   been paced-out and the server realises the shorter RTT.

   If it happens the client's RTT is larger (for whatever reason), the
   rate of tranbsmission remains the same, but paced-sending ceases
   before the RTT. This is better than not trying to adjust the paced-IW
   to the RTT, but less than could have been achieved.

**Comment by NicoKos** [comment]
I need some more time to go deeper into this, but I like the idea very much.
I will try to put some text in that sense.

**Comment by gorryfair** [comment]
Sure ... I think we need to reflect on the proposal and judge the benefit, at least for me this would seem to save 2-3 RTTs on a satellite path ;-). Saving more is likely dangerous ... because the next round of cwnd increase becomes increasingly large (it's exponential!) and we need to avoid being overly aggressive (even to ourselves). 

I suggest you reflect and discuss as needed...

**Comment by gorryfair** [comment]
I don't mind it in the draft - or an annexe as an example until we are ready? ... our just discussing it really doesn't matter - but we need to have more thoughts ourselves, by seeing how this works out.

**Comment by gorryfair** [comment]
So ... after more thought, I think I conclude that _this could be not too bad at avoiding starvation_ of other flows sharing a path, but it could cause _**congestion collapse**_. Here is why: There is no initial check that the path isn't already _**on the edge of congestion collapse**_ before the faster ramp-up to send a large number of segments! Once congested, every new flow makes its substantially more overloaded.
* Example: Suppose a node is massively congested at the time when the flow starts.... Then this will force ~60 packets (jumping immediately to the higher rate)  into that congested node in an RTT for **EACH** new connection. Even if the flow experiences massive loss, any new flow using the method will start in exactly the same way, possibly from the same endpoint, or some other endpoint behind the same overloaded node. (Traditional TCP would have seen loss of the SYN or loss of the initial IW - both of which should have prevented more segments being sent on the path. This is much, much, worse - because there is no feedback before injecting the initial data.)
* I think it would be *MUCH* safer if we did not send more than IW in the first RTT. So, let me propose something different: Suppose we limit to only send IW in **the first RTT**, and check that all IW data crossed the path - and the RTT was not much above the min_RTT we had signalled... **before** we jump to the higher rate. Wouldn't that confirm at this time the nodes on path were not in massive congestion??? (after all, we have now sent IW segments without loss - and we could look at observed RTT and confirm this also is within limits if we wished). In the second RTT, we can now use the initial information and can argue it would be OK to send paced data at a MUCH higher rate, paced over the RTT that we observed, has little chance that it causes congestion collapse ... if our transmission jumping to this higher rate has caused the path to now congest, any additional new flow wouldn't get IW data through now ... so that new flow couldn't repeat the "jump" to a higher rate inducing collapse. We have avoided congestion collapse.
* True, this doesn't allow as much to complete in one RTT - but it does have much greater safety and a current PEP never completes in one RTT using TCP anyway, so it's just as good.
.... Has this thinking re-invented BBR or JumpStart?

**Comment by NicoKos** [comment]
I think that I understand your proposal that I try to sum up here : 
1- the server keeps a standard IW to avoid adding congestion to a congested network
2- after the reception of the ACK for the IW packets, the server checks min_rtt is consistent and adapt the congestion window to a higher value that must be paced out
The initial_max_pkt_number would be the amount of data the server would send during more time than the next two RTT.  The pacing rate should then be (initial_max_pkt_number-IW)/min_rtt/2 

The objective of the document is to allow exchange of parameters that are going to be used but not detail how they are configured by the server/client. That being said, this example could be added as a potential server solution in the Appendix of the document.
The core of the document could say that if the server increases the initial_max_pkt_number, avoiding congestion collapse should be in the design of the congestion control.

What do you think?

**Comment by gorryfair** [comment]
Close enough to be useful - go for this... :-)

Gorry

**Comment by NicoKos** [comment]
Proposed text in PR #92
