### ISSUE TITLE
I don't think the ack_ratio is a helpful param.

### ISSUE THREAD

**Issue by gorryfair** [NicoKos/QUIC_HIGH_BDP#89]
ack_ratio (0x000X): The acknowledgment ratio that has been used at
      the end of the previous connection by the server or the
      acknowledgment ratio that the server is willing to use.  It is an
      integer in unit of packets.

I thought at first this would be useful, but I'll now argue against. There are three reasons:

(1) I think we should argue that QUIC's default method allows a 1:10 ratio... that is already a major win, and if this is a default, it is likely to be widely implemented. Adding this helps in some corner cases, but risks the bigger gain of all doing 1:10.

(2) I think even a ratio of 10 needs to be used with care at start-up. So the best method is starting with 1:2 for the initial 100 packets. That means that you do not need this as initial data. The decision to use it later needs to be made later in the connection.

(3) I'll argue strongly against Christian's idea of a signalled ACK ratio until we understand the implications on CC. I think others may share my concern - and some think this can only be considered in v2, that there can be very serious implications of changing the ACK Ratio larger than the IW, because both contribute bursts and sharing issues for the path - the idea of scaling ACK Ratio  really needs to be justified. This has the potential to further increase the ACK Ratio to scenarios where a larger ACK Ratio may have benefit. To me this needs evidence of safety (because it goes beyond the assumptions that motivated the QUIC to allow IW bursts). 

I'll argue we should remove the option to avoid this - rather than pushing the whole idea to a later v2 proposal.

**Comment by NicoKos** [comment]
Thanks for this comment. 
We have included it to have the discussion in the draft as this is what I understood from our call. 
That being said, I understand your point.

How about including it in the discussion section in case the current document in case it does not make it to default ?

**Comment by gorryfair** [comment]
I will argue against the param bing a part of this (but later), so for now let's work out what happens with ACKs during slow-start. The idea to postpone a change to the ACK Ratio (keeping 1:2) after the first 100 packets have been received came form discussions with google, and makes sense with respect to emulating DAASS from TCP. Is this an issue for QUIC-CC? This needs thought, but likely depends on the CC (for RENO it does, and setting 1:10 delays the initial window growth in the next RTT) ... if it is a real issue, then it applies also during the "improved" initial data exchange we are discussing... and we need to understand that.

**Comment by NicoKos** [comment]
I see. Due to the link between the strawman algo and the CC, we may not have enough data to see how to tune the ACK ratio during the life of a session. 
If I move it back to the discussion section, would that be OK ? (mentioning it is future work and depends on how the ACK_ratio is managed in the standard?

**Comment by gorryfair** [comment]
It's OK to mention it - and I think with a little more thought we can propose a concrete use that makes sense. You still need the info from the previous flow to do this, whatever.

**Comment by NicoKos** [comment]
Text proposed in PR #94
