### ISSUE TITLE
Is ACK Ratio still a good example?

### ISSUE THREAD

**Issue by gorryfair** [NicoKos/QUIC_HIGH_BDP#9]
ACK Ratio is a good exmaple of a problem and the text state:
"As example, the client could adapt the ACK ratio"
- however we discussed if this draft could potentially be considered in QUICv1, and I see from the QUIC git that this topic has now been postponed to QUICv2. It may serve us better to cite optimisations that can be achieved with QUICv1?

**Comment by NicoKos** [comment]
You are right, this not relevant - closed by PR #16
