### ISSUE TITLE
Supplementary metric in the QUIC 4 SAT document 

### ISSUE THREAD

**Issue by NicoKos** [NicoKos/QUIC_HIGH_BDP#96]
Is it relevant to add a metric on "how long it took the congestion control to reach the bottleneck capacity"?

**Comment by NicoKos** [comment]
Maybe adding this metric is very complicated, such as mentionned by Tom on the phone. 
I would propose changing : 
"The test should report the downloading time of 100 MB from the
   Internet to the host." 
by 
"During the transmission of 100MB, the test should report the downloading time of 2MB, 50MB and 100 MB from the Internet to the host."

This would let us assess the "getting up to speed" performance of the QUIC implementation. 
What do you think?

**Comment by emile22** [comment]
+1, we might add one at 5 MB and 10 MB too

**Comment by NicoKos** [comment]
I would rather have 
2MB, 10MB, 100MB
or 
5MB, 10MB, 100MB

I am affraid that multiplicating the metrics may not ease the acceptation from others.

**Comment by NicoKos** [comment]
I pushed an updated version of the tests in the commit : https://github.com/NicoKos/QUIC_HIGH_BDP/commit/1abd79e8d85222f6372a70c6178e36b388e0fbe0
